replication_factor = 1

metadata_dir = "/var/lib/garage/meta"
data_dir = "/var/lib/garage/data"
metadata_snapshots_dir = "/var/lib/garage/snapshots"
metadata_auto_snapshot_interval = "24h"

db_engine = "lmdb"


rpc_bind_addr = "[::]:3901"
rpc_secret_file = ".secrets/rpc_secret.txt"

bootstrap_peers = []

[s3_api]
api_bind_addr = "[::]:3900"
s3_region = "garage"

[s3_web]
bind_addr = "[::]:3902"
root_domain = "localhost"
